# Generated by Django 4.2.3 on 2023-10-20 14:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('host', models.CharField(blank=True, max_length=256)),
                ('category', models.CharField(blank=True, max_length=256)),
                ('number_of_inscriptions', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('max_number_of_inscriptions', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('date', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=64)),
                ('url_location', models.CharField(max_length=1024)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000)])),
                ('equipaments', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventsPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.places')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='place',
            field=models.ManyToManyField(through='events.EventsPlaces', to='events.places'),
        ),
    ]
