# Generated by Django 4.2.3 on 2023-10-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='course_time',
            field=models.CharField(blank=True, default='00:00:00-00:00:00', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='date_end',
            field=models.DateTimeField(default='2023-12-12T00:00:00.000000Z'),
        ),
        migrations.AddField(
            model_name='events',
            name='date_start',
            field=models.DateTimeField(default='2023-12-12T00:00:00.000000Z'),
        ),
    ]
