# Generated by Django 4.2.3 on 2024-10-31 23:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_list', to='events.events')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.JSONField(blank=True, default=list)),
                ('hours_per_day', models.JSONField(blank=True, default=list)),
                ('attendance_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.attendancelist')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
