# Generated by Django 4.2.3 on 2023-10-20 20:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='user', max_length=64)),
                ('email', models.EmailField(max_length=512, unique=True)),
                ('password', models.CharField(max_length=256, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_name', models.CharField(blank=True, default='', max_length=64)),
                ('ies', models.CharField(blank=True, default='', max_length=256)),
                ('birthday', models.DateField(blank=True, default='2000-01-01')),
                ('cpf', models.CharField(blank=True, default='', max_length=11)),
                ('course', models.CharField(blank=True, default='', max_length=256)),
                ('semester', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(48)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_salt', models.CharField(max_length=16)),
                ('hash_algorithm', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('email_validation_token', models.CharField(max_length=128, unique=True)),
                ('email_validation', models.BooleanField(default=False)),
                ('token_generation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='users.user')),
            ],
        ),
    ]
