# Generated by Django 4.2.3 on 2023-10-17 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=24)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('all_speeches', models.BooleanField(default=False)),
                ('workshops', models.IntegerField(blank=True, default=0)),
                ('bucks_coup', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Kits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payed', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=24)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KitsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kits.kits')),
            ],
        ),
        migrations.AddField(
            model_name='kits',
            name='events',
            field=models.ManyToManyField(through='kits.KitsEvents', to='events.events'),
        ),
        migrations.AddField(
            model_name='kits',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
